import type { Metadata } from "next";
import "./globals.css";
import {SessionProvider} from "next-auth/react";
import { Toaster } from "sonner";
import {TooltipProvider} from "@/components/ui/tooltip";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={``}
      >
      <SessionProvider>
          <TooltipProvider>
          {children}
          <Toaster position="top-right" />
          </TooltipProvider>
      </SessionProvider>
      </body>
    </html>
  );
}
